"""Query Engine: 構造化された文章検索DSL。"""
from __future__ import annotations

from query_engine.adapters import (
                                   CsvAdapter,
                                   DocumentAdapter,
                                   DocumentLoadIssue,
                                   JsonAdapter,
                                   TextDocument,
                                   TextTableAdapter,
                                   csv_to_documents,
                                   extract_text_file,
                                   from_text,
                                   from_text_file,
                                   iter_json_documents,
                                   iter_json_records,
                                   json_to_documents,
                                   load_csv,
                                   load_json,
                                   load_text_table,
                                   log_to_document,
                                   normalize_document,
                                   normalize_text,
                                   row_to_document,
                                   rows_to_documents,
                                   text_table_to_documents,
)
from query_engine.ast import AndNode, CompareNode, EmptyNode, FieldNode, NotNode, OrNode, PhraseNode, QueryNode, RegexNode, TermNode
from query_engine.evaluators.memory import match_query, search
from query_engine.evaluators.sql import SqlCompileResult, compile_sql_where
from query_engine.models import QueryDocument, SearchQuery, SearchResult, SortSpec
from query_engine.parser import GRAMMAR, QuerySyntaxError, parse, parse_query, tokenize

__all__: list[str] = [
    "AndNode",
    "CompareNode",
    "CsvAdapter",
    "DocumentAdapter",
    "DocumentLoadIssue",
    "EmptyNode",
    "FieldNode",
    "GRAMMAR",
    "JsonAdapter",
    "NotNode",
    "OrNode",
    "PhraseNode",
    "QueryNode",
    "QueryDocument",
    "QuerySyntaxError",
    "RegexNode",
    "SearchQuery",
    "SearchResult",
    "SqlCompileResult",
    "SortSpec",
    "TermNode",
    "TextDocument",
    "TextTableAdapter",
    "compile_sql_where",
    "csv_to_documents",
    "extract_text_file",
    "from_text",
    "from_text_file",
    "iter_json_documents",
    "iter_json_records",
    "json_to_documents",
    "load_csv",
    "load_json",
    "load_text_table",
    "log_to_document",
    "match_query",
    "normalize_text",
    "normalize_document",
    "parse",
    "parse_query",
    "row_to_document",
    "rows_to_documents",
    "search",
    "text_table_to_documents",
    "tokenize",
]
